In [1]:
'''
As hammoq provides api to fetch historical data posted by customers.
Analysing that data to look for most frequent attributes and their corresponding values 
can help us to decide on keywords that we chose to scrap similar data from other platforms

This notebook provides methods to process json files coming from hammoq api, build dataframe out of these files and
perform histogram based visual analysis for attributes and corresponding values.

'''

'\nAs hammoq provides api to fetch historical data posted by customers.\nAnalysing that data to look for most frequent attributes and their corresponding values \ncan help us to decide on keywords that we chose to scrap similar data from other platforms\n\nThis notebook provides methods to process json files coming from hammoq api, build dataframe out of these files and\nperform histogram based visual analysis for attributes and corresponding values.\n\n'

In [2]:
import os
import pandas as pd
from collections import Counter
import json
from matplotlib import pyplot as plt

In [7]:
def get_dataframe_from_json_folder(json_folder_path='./'):
    '''
    read json files from given path and build list of dictionaries base on json strings
    '''
    json_folder_path = json_folder_path
    all_jsons=[]
    for root, directories, files in os.walk(json_folder_path, topdown=False):
        for name in files:
            f=(os.path.join(root, name))
            if f.endswith((".json")):
                all_jsons.append(f)
    '''
    read json files and build list of dictionaries base on json strings
    '''

    dcts=[]
    for json_file in all_jsons:
        with open(json_file,'r') as f:
            data= eval(json.load(f))
            dcts.append(data)
    '''
    build dataframe from list of dictionaries
    '''
    _df=pd.DataFrame(dcts)
    return _df

In [8]:
#get_dataframe_from_json_folder('./')

In [9]:
'''
read json files from given path and build list of dictionaries base on json strings
'''
all_jsons=[]
for root, directories, files in os.walk("./", topdown=False):
    for name in files:
        f=(os.path.join(root, name))
        if f.endswith((".json")):
            all_jsons.append(f)

In [10]:
#all_jsons

In [11]:
'''
read json files and build list of dictionaries base on json strings
'''

dcts=[]
for json_file in all_jsons:
    with open(json_file,'r') as f:
        data= eval(json.load(f))
        dcts.append(data)
'''
build dataframe from list of dictionaries
'''
main_df=pd.DataFrame(dcts)

In [12]:
main_df

,id,REQUIRED,RECOMMENDED,OPTIONAL
0,841,[],[],"[{'Color': ['Beige', 'Black', 'Blue', 'Brown',..."
1,965,[],[],"[{'Decade': ['Pre 1890', '1890s', '1900s', '19..."
2,957,[],[],"[{'Decade': ['Pre 1890', '1890s', '1900s', '19..."
3,843,[],[],"[{'Type of Advertising': ['Print Ad', 'Sign', ..."
4,2996,"[{'Brand': ['!it', '& Other Stories', '10.Deep...","[{'Theme': ['3D', '80s', '90s', 'Aloha', 'Amer...","[{'Pattern': ['Animal Print', 'Argyle/Diamond'..."
...,...,...,...,...
612,18786,"[{'Type': ['Bandana', 'Barrette', 'Bobby Pin',...","[{'Department': ['Baby', 'Boys', 'Girls']}, {'...","[{'Accents': ['Beaded', 'Bow', 'Buckle', 'Butt..."
613,11511,"[{'Brand': ['!it', '& Other Stories', '+8000',...","[{'Sock Length': ['No-Show', 'Low Cut', 'Mid C...","[{'Character Family': ['Angry Birds', 'Astro B..."
614,175807,[],"[{'Brand': ['Accessory Street', 'Adrienne Vitt...","[{'Look': ['Androgyny', 'Art Deco', 'Arts & Cr..."
615,20864,"[{'Brand': ['3N2', '94Fify', 'A&R', 'A4', 'Ace...","[{'Sport/Activity': ['Soccer']}, {'Size': ['XX...","[{'Color': ['Beige', 'Black', 'Blue', 'Brown',..."
616,175780,[],"[{'Decade': ['Pre 1890', '1890s', '1900s', '19...","[{'Color': ['Beige', 'Black', 'Blue', 'Bronze'..."

In [30]:
'''
process RECEOMMENDED column of dataframe df
'''
'''
recommended_lsts = []
recommended_dcts=[]
for datums in main_df.RECOMMENDED:
    recommended_lsts.append(datums)
    for dct in datums:
        recommended_dcts.append(dct)
'''

'\nrecommended_lsts = []\nrecommended_dcts=[]\nfor datums in main_df.RECOMMENDED:\n    recommended_lsts.append(datums)\n    for dct in datums:\n        recommended_dcts.append(dct)\n'

### methods for attributes and corresponding values analysis

In [14]:
'''
method to get list of attributes with their frequencies in given columns of dataframe
input: dataframe, name of column {default=RECOMMENDED}
output: attributes frequency tabel
'''
def get_attributes_from_df(dataframe,column_name='RECOMMENDED'):
    lsts = []
    dcts=[]
    for datums in dataframe[column_name]:
        lsts.append(datums)
        for dct in datums:
            dcts.append(dct)
    attributes=[]
    for lst in lsts:
        for dct in lst:
            for key in dct.keys():
                attributes.append(key)
    #attrib_freq=sorted(Counter(attributes).items(), key=lambda item: item[1],reverse=True)
    return list(Counter(attributes).keys())

def get_attributes_freq_from_df(dataframe,column_name='RECOMMENDED'):
    lsts = []
    dcts=[]
    for datums in dataframe[column_name]:
        lsts.append(datums)
        for dct in datums:
            dcts.append(dct)
    attributes=[]
    for lst in lsts:
        for dct in lst:
            for key in dct.keys():
                attributes.append(key)
    return sorted(Counter(attributes).items(), key=lambda item: item[1],reverse=True)

In [15]:
#get_attributes_from_df(get_dataframe_from_json_folder('./'),'RECOMMENDED')

In [16]:
'''
define method to get values for given attribute
'''

'\ndefine method to get values for given attribute\n'

In [17]:
def get_vals_for_attrib(attrib,dataframe,column_name='RECOMMENDED'):
    dcts = []
    vals = []
    for lst in dataframe[column_name]:
        for dct in lst:
            dcts.append(dct)
    for i in dcts:
        if attrib in list(i.keys()):
            if isinstance(i[attrib],str):
                vals.append(i[attrib])
            elif isinstance(i[attrib],list):
                for val in i[attrib]:
                    vals.append(val)
            else:
                pass
    return list(Counter(vals).keys())

In [20]:
get_vals_for_attrib('Style',main_df,'REQUIRED')

['Cape',
 'Full Zip',
 'Henley',
 'Pullover',
 'Ballet',
 'Biker',
 'Boat Shoe',
 'Bootie',
 'Brogue',
 'Chelsea',
 'Chukka',
 'Clog',
 'Combat',
 "D'Orsay",
 'Derby',
 'Desert',
 'Espadrille',
 'Fisherman',
 'Flat',
 'Flip Flop',
 'Gladiator',
 'Loafer',
 'Mary Jane',
 'Moccasin',
 'Monk Strap',
 'Mule',
 'Oxford',
 'Platform',
 'Pump',
 'Rain Boot',
 'Shearling Style',
 'Slide',
 'Slingback',
 'Slip-On',
 'Sneaker',
 'Snow Boot',
 'Sock',
 'Strappy',
 'Thong',
 'Western',
 '3-in-1 Jacket',
 'Anorak',
 'Basic Jacket',
 'Bomber Jacket',
 'Kimono',
 'Military Jacket',
 'Motorcycle Jacket',
 'Overcoat',
 'Parka',
 'Pea Coat',
 'Puffer Jacket',
 'Quilted',
 'Rain Coat',
 'Trench Coat',
 'Varsity Jacket',
 'Windbreaker',
 'Boxer Brief',
 'Boxer Shorts',
 'Boyshort',
 'Brief',
 'Full Slip',
 'Half Slip',
 'High-Waisted',
 'Hipster',
 'One Piece',
 'Split Slip',
 'Tank',
 'Tap Pants',
 'Capri',
 'Cargo',
 'Carpenter',
 'Carrot',
 'Chino',
 'Cropped',
 'Harem',
 'Jegging',
 'Jogger',
 'Pedal Pusher',
 'Arm Warmers',
 'Boot Cuffs',
 'Boot Toppers',
 'Cuff',
 'Ankle Socks',
 'Athletic Socks',
 'Bed/Slipper Socks',
 'Crawling Tights',
 'Knee Highs',
 'Leg Warmers',
 'Toe Socks',
 'Athletic',
 'Compression',
 'Hot Pants',
 'Sweat',
 'Camisole',
 'Cheeky',
 'Chest Binder',
 'Long Johns',
 'Shaping Top',
 'Top',
 'Ski Jacket',
 'Track Jacket',
 'Cardigan',
 'Shrug',
 'Tunic',
 'Vest',
 'Wrap',
 'Fleece',
 'A-Line',
 'Ball Gown',
 'Fit & Flare',
 'Jacket Dress',
 'Kaftan',
 'Maxi',
 'Mermaid',
 'Mini',
 'Overall Dress',
 'Pencil Dress',
 'Sheath',
 'Shift',
 'Shirt Dress',
 'Skater Dress',
 'Sundress',
 'Sweater Dress',
 'Tank Dress',
 'Tennis Dress',
 'Trapeze & Swing',
 'T-Shirt Dress',
 'Tutu Dress',
 'Wrap Dress',
 'Bandage',
 'Flare',
 'Peasant',
 'Pettiskirt',
 'Pleated',
 'Skater',
 'Straight & Pencil',
 'Swing',
 'Trumpet',
 'Tulip',
 'Tutu',
 'Bloomer',
 'Dress Pants',
 'Overalls',
 'Rain Pants',
 'Snow Pants',
 'Sweatpants',
 'Bermuda',
 'Shortalls',
 'Utility',
 'Control Top Tights',
 'Crotchless Tights',
 'Knitted Tights',
 'Mock Suspender Tights',
 'Shaper Tights',
 'Shimmery Tights',
 'Suspender Tights',
 'Thermal Tights',
 'Sports Bra',
 '5 Panel',
 'Army Cap',
 'Aviator/Pilot',
 'Balaclava',
 'Bandana',
 'Baseball Cap',
 'Beanie',
 'Beret',
 'Bobble Hat',
 'Bonnet',
 'Boonie Hat',
 'Boshi',
 'Bowler Hat',
 'Bucket Hat',
 'Capuchon',
 'Cloche',
 'Cossack',
 'Cowboy Hat',
 'Docker Cap',
 'Do-rag',
 'Fedora',
 'Flat Cap',
 'Golf Hat',
 'Headband',
 'Headpiece/Fascinator',
 'Hijab',
 'Homburg Hat',
 'Newsboy Cap',
 'Panama Hat',
 'Papakha',
 'Peaked Cap',
 'Pork Pie',
 'Skull Cap',
 'Slouch Hat',
 'Snapback',
 'Sun Hat',
 'Taqiyah',
 'Top Hat',
 'Trapper Hat',
 'Trilby',
 'Trucker Hat',
 'Turban',
 'Visor',
 'Track Pants',
 'Bootcut',
 'Boyfriend',
 'Flared',
 'Skinny',
 'Straight',
 'Tapered',
 'Wide-Leg',
 'Corselette',
 'Girdle',
 'Jockstrap',
 'Shaping Bottom',
 'Torsette',
 'Waist Trainer',
 'Backpack',
 'Belt Bag & Fanny Pack',
 'Book Bag',
 'Briefcase',
 'Bucket & Drawstring Bag',
 'Clutch',
 'Crossbody',
 'Duffle',
 'Gym Bag',
 'Hobo Bag',
 'Laptop Bag',
 'Messenger Bag',
 'Pouch',
 'Randoseru',
 'Saddle Bag',
 'Satchel',
 'Shoulder Bag',
 'Tote',
 'Basic Coat',
 'Duffle Coat',
 'Shirt Jacket',
 'Ski Salopettes',
 'Pant Suit',
 'Shorts Suit',
 'Skirt Suit',
 'Tuxedo',
 "Mariner's cap",
 'Anti-Skid Socks',
 'Calf Socks',
 'Crew Socks',
 'Dress Socks',
 'No-Show Socks',
 'Novelty Socks',
 'Outdoor Socks',
 'School Socks',
 'Sneaker Socks',
 'Trainer Liners',
 'Skort',
 'Thong/String',
 'Culotte',
 'Cut-Off',
 'Mom',
 'Paperbag',
 'Sailor',
 'Skimmer',
 '2 Piece',
 '3 Piece',
 'Overpants',
 'Ballet Socks',
 'Bobby Socks',
 'Boot Socks',
 'Diabetic',
 'Fuzzy Socks',
 'Grip Socks',
 'Tabi Socks',
 'Thermal Socks',
 'Toe Covers',
 'Turn Cuff Socks',
 'Welly Socks',
 'Crinoline',
 'Petticoat',
 'Bikini',
 'Wading Boots',
 'Rain Poncho',
 'Rain Suit',
 'Wading Jacket',
 'Windshirt',
 'Windstopper',
 'Footless Tights',
 'Overknees',
 'Narrow Belt',
 'Standard Belt',
 'Wide Belt',
 'Cami',
 'Corset Dress',
 'Corset Shirt',
 'Corset Top',
 'Overbust',
 'Underbust',
 'Vest Top',
 'Victorian',
 'Waist Cincher',
 'Adhesive Bra',
 'Balconette Bra',
 'Bandeau Bra',
 'Bralette',
 'Harness Bra',
 'Longline Bra',
 'Mastectomy Bra',
 'Minimizer Bra',
 'Nursing Bra',
 'Push Up Bra',
 'Stick on Bra',
 'Training Bra',
 'T-Shirt Bra',
 'Breezer',
 'Head Net',
 'Wide Brim',
 'Blouson',
 'Bodycon',
 'Slip Dress',
 'Bra Clasp',
 'Bra Converter Strap',
 'Bra Extender',
 'Bra Inserts',
 'Bra Strap Clip',
 'Bra Strap Cushions',
 'Bra Strap Ring & Slider',
 'Bra Straps',
 'Bra Underwire',
 'Breast Forms',
 'Breast Petals',
 'Fillets',
 'Nipple Covers',
 'Nipple Enhancers',
 'Tape',
 'Body Stockings',
 'Fishnet',
 'Garter',
 'Regular Stockings',
 'Shaping',
 'Suspender',
 'Thermal',
 'Footless']

In [19]:
def get_vals_freq_for_attrib(attrib,dataframe,column_name='RECOMMENDED'):
    dcts = []
    vals = []
    for lst in dataframe[column_name]:
        for dct in lst:
            dcts.append(dct)
    for i in dcts:
        if attrib in list(i.keys()):
            if isinstance(i[attrib],str):
                vals.append(i[attrib])
            elif isinstance(i[attrib],list):
                for val in i[attrib]:
                    vals.append(val)
            else:
                pass
    return sorted(Counter(vals).items(),key=lambda item: item[1],reverse=True)

In [21]:
#get_vals_freq_for_attrib('Style',main_df,'REQUIRED')

[('Biker', 23),
 ('Windbreaker', 21),
 ('Compression', 21),
 ('Cargo', 19),
 ('Cropped', 18),
 ('Full Zip', 15),
 ('Henley', 15),
 ('Pullover', 15),
 ('Capri', 15),
 ('Loafer', 14),
 ('Slip-On', 14),
 ('Wrap', 14),
 ('Jegging', 13),
 ('Jogger', 13),
 ('Cape', 12),
 ('Slide', 12),
 ('3-in-1 Jacket', 12),
 ('Chino', 12),
 ('Basic Jacket', 11),
 ('Varsity Jacket', 11),
 ('Rain Pants', 11),
 ('Sweatpants', 11),
 ('Bootie', 10),
 ('Fisherman', 10),
 ('Flip Flop', 10),
 ('Mule', 10),
 ('Sweat', 10),
 ('Track Jacket', 10),
 ('Vest', 10),
 ('Snow Pants', 10),
 ('Clog', 9),
 ('Moccasin', 9),
 ('Shearling Style', 9),
 ('Sneaker', 9),
 ('Pedal Pusher', 9),
 ('Athletic', 9),
 ('Ski Jacket', 9),
 ('Cardigan', 9),
 ('Boat Shoe', 8),
 ('Espadrille', 8),
 ('Flat', 8),
 ('Rain Boot', 8),
 ('Sock', 8),
 ('One Piece', 8),
 ('Tank', 8),
 ('A-Line', 8),
 ('Maxi', 8),
 ('Boyfriend', 8),
 ('Oxford', 7),
 ('Platform', 7),
 ('Slingback', 7),
 ('Snow Boot', 7),
 ('Thong', 7),
 ('Western', 7),
 ('Anorak', 7),
 ('Rain Coat', 7),
 ('Brief', 7),
 ('High-Waisted', 7),
 ('Carpenter', 7),
 ('Carrot', 7),
 ('Harem', 7),
 ('Mini', 7),
 ('Do-rag', 7),
 ('Ballet', 6),
 ('Chelsea', 6),
 ('Chukka', 6),
 ('Combat', 6),
 ('Desert', 6),
 ('Gladiator', 6),
 ('Bomber Jacket', 6),
 ('Military Jacket', 6),
 ('Motorcycle Jacket', 6),
 ('Overcoat', 6),
 ('Parka', 6),
 ('Pea Coat', 6),
 ('Puffer Jacket', 6),
 ('Quilted', 6),
 ('Trench Coat', 6),
 ('Full Slip', 6),
 ('Half Slip', 6),
 ('Athletic Socks', 6),
 ('Knee Highs', 6),
 ('Hot Pants', 6),
 ('Tunic', 6),
 ('Balaclava', 6),
 ('Bandana', 6),
 ('Baseball Cap', 6),
 ('Beanie', 6),
 ('Boonie Hat', 6),
 ('Docker Cap', 6),
 ('Flat Cap', 6),
 ('Newsboy Cap', 6),
 ('Panama Hat', 6),
 ('Top Hat', 6),
 ('Trucker Hat', 6),
 ('Track Pants', 6),
 ('Mary Jane', 5),
 ('Strappy', 5),
 ('Kimono', 5),
 ('Boxer Shorts', 5),
 ('Boyshort', 5),
 ('Hipster', 5),
 ('Ankle Socks', 5),
 ('Bed/Slipper Socks', 5),
 ('Toe Socks', 5),
 ('Long Johns', 5),
 ('Shaping Top', 5),
 ('Shrug', 5),
 ('Flare', 5),
 ('Skater', 5),
 ('Tutu', 5),
 ('Bloomer', 5),
 ('Dress Pants', 5),
 ('Overalls', 5),
 ('Bermuda', 5),
 ('5 Panel', 5),
 ('Army Cap', 5),
 ('Beret', 5),
 ('Bowler Hat', 5),
 ('Bucket Hat', 5),
 ('Cowboy Hat', 5),
 ('Fedora', 5),
 ('Golf Hat', 5),
 ('Headband', 5),
 ('Headpiece/Fascinator', 5),
 ('Hijab', 5),
 ('Homburg Hat', 5),
 ('Papakha', 5),
 ('Peaked Cap', 5),
 ('Pork Pie', 5),
 ('Skull Cap', 5),
 ('Slouch Hat', 5),
 ('Snapback', 5),
 ('Trapper Hat', 5),
 ('Trilby', 5),
 ('Turban', 5),
 ('Visor', 5),
 ('Bootcut', 5),
 ('Flared', 5),
 ('Skinny', 5),
 ('Straight', 5),
 ('Tapered', 5),
 ('Wide-Leg', 5),
 ('Girdle', 5),
 ('Shaping Bottom', 5),
 ('Basic Coat', 5),
 ('Crew Socks', 5),
 ('Dress Socks', 5),
 ('Novelty Socks', 5),
 ('Outdoor Socks', 5),
 ('Sneaker Socks', 5),
 ('Brogue', 4),
 ("D'Orsay", 4),
 ('Derby', 4),
 ('Monk Strap', 4),
 ('Boxer Brief', 4),
 ('Split Slip', 4),
 ('Tap Pants', 4),
 ('Chest Binder', 4),
 ('Shortalls', 4),
 ('Utility', 4),
 ('Aviator/Pilot', 4),
 ('Bobble Hat', 4),
 ('Bonnet', 4),
 ('Boshi', 4),
 ('Capuchon', 4),
 ('Cloche', 4),
 ('Cossack', 4),
 ('Sun Hat', 4),
 ('Taqiyah', 4),
 ('Duffle Coat', 4),
 ('Shirt Jacket', 4),
 ('Ski Salopettes', 4),
 ('Tuxedo', 4),
 ('Anti-Skid Socks', 4),
 ('Calf Socks', 4),
 ('No-Show Socks', 4),
 ('School Socks', 4),
 ('Trainer Liners', 4),
 ('Mom', 4),
 ('Cheeky', 3),
 ('Fit & Flare', 3),
 ('Jacket Dress', 3),
 ('Kaftan', 3),
 ('Mermaid', 3),
 ('Overall Dress', 3),
 ('Sheath', 3),
 ('Shift', 3),
 ('Shirt Dress', 3),
 ('Sundress', 3),
 ('Sweater Dress', 3),
 ('Tank Dress', 3),
 ('Trapeze & Swing', 3),
 ('T-Shirt Dress', 3),
 ('Wrap Dress', 3),
 ('Pettiskirt', 3),
 ('Pleated', 3),
 ('Trumpet', 3),
 ('Corselette', 3),
 ('Torsette', 3),
 ('Waist Trainer', 3),
 ('Backpack', 3),
 ('Belt Bag & Fanny Pack', 3),
 ('Briefcase', 3),
 ('Crossbody', 3),
 ('Duffle', 3),
 ('Gym Bag', 3),
 ('Laptop Bag', 3),
 ('Messenger Bag', 3),
 ('Pouch', 3),
 ('Saddle Bag', 3),
 ('Satchel', 3),
 ('Shoulder Bag', 3),
 ('Tote', 3),
 ('Pant Suit', 3),
 ('Shorts Suit', 3),
 ('Thong/String', 3),
 ('Culotte', 3),
 ('Cut-Off', 3),
 ('Paperbag', 3),
 ('Sailor', 3),
 ('Skimmer', 3),
 ('Crinoline', 3),
 ('Petticoat', 3),
 ('Bikini', 3),
 ('Pump', 2),
 ('Leg Warmers', 2),
 ('Ball Gown', 2),
 ('Pencil Dress', 2),
 ('Skater Dress', 2),
 ('Tennis Dress', 2),
 ('Tutu Dress', 2),
 ('Bandage', 2),
 ('Peasant', 2),
 ('Straight & Pencil', 2),
 ('Swing', 2),
 ('Tulip', 2),
 ('Jockstrap', 2),
 ('Bucket & Drawstring Bag', 2),
 ('Clutch', 2),
 ('Hobo Bag', 2),
 ('Skirt Suit', 2),
 ('Overknees', 2),
 ('Cami', 2),
 ('Overbust', 2),
 ('Underbust', 2),
 ('Victorian', 2),
 ('Stick on Bra', 2),
 ('Arm Warmers', 1),
 ('Boot Cuffs', 1),
 ('Boot Toppers', 1),
 ('Cuff', 1),
 ('Crawling Tights', 1),
 ('Camisole', 1),
 ('Top', 1),
 ('Fleece', 1),
 ('Control Top Tights', 1),
 ('Crotchless Tights', 1),
 ('Knitted Tights', 1),
 ('Mock Suspender Tights', 1),
 ('Shaper Tights', 1),
 ('Shimmery Tights', 1),
 ('Suspender Tights', 1),
 ('Thermal Tights', 1),
 ('Sports Bra', 1),
 ('Book Bag', 1),
 ('Randoseru', 1),
 ("Mariner's cap", 1),
 ('Skort', 1),
 ('2 Piece', 1),
 ('3 Piece', 1),
 ('Overpants', 1),
 ('Ballet Socks', 1),
 ('Bobby Socks', 1),
 ('Boot Socks', 1),
 ('Diabetic', 1),
 ('Fuzzy Socks', 1),
 ('Grip Socks', 1),
 ('Tabi Socks', 1),
 ('Thermal Socks', 1),
 ('Toe Covers', 1),
 ('Turn Cuff Socks', 1),
 ('Welly Socks', 1),
 ('Wading Boots', 1),
 ('Rain Poncho', 1),
 ('Rain Suit', 1),
 ('Wading Jacket', 1),
 ('Windshirt', 1),
 ('Windstopper', 1),
 ('Footless Tights', 1),
 ('Narrow Belt', 1),
 ('Standard Belt', 1),
 ('Wide Belt', 1),
 ('Corset Dress', 1),
 ('Corset Shirt', 1),
 ('Corset Top', 1),
 ('Vest Top', 1),
 ('Waist Cincher', 1),
 ('Adhesive Bra', 1),
 ('Balconette Bra', 1),
 ('Bandeau Bra', 1),
 ('Bralette', 1),
 ('Harness Bra', 1),
 ('Longline Bra', 1),
 ('Mastectomy Bra', 1),
 ('Minimizer Bra', 1),
 ('Nursing Bra', 1),
 ('Push Up Bra', 1),
 ('Training Bra', 1),
 ('T-Shirt Bra', 1),
 ('Breezer', 1),
 ('Head Net', 1),
 ('Wide Brim', 1),
 ('Blouson', 1),
 ('Bodycon', 1),
 ('Slip Dress', 1),
 ('Bra Clasp', 1),
 ('Bra Converter Strap', 1),
 ('Bra Extender', 1),
 ('Bra Inserts', 1),
 ('Bra Strap Clip', 1),
 ('Bra Strap Cushions', 1),
 ('Bra Strap Ring & Slider', 1),
 ('Bra Straps', 1),
 ('Bra Underwire', 1),
 ('Breast Forms', 1),
 ('Breast Petals', 1),
 ('Fillets', 1),
 ('Nipple Covers', 1),
 ('Nipple Enhancers', 1),
 ('Tape', 1),
 ('Body Stockings', 1),
 ('Fishnet', 1),
 ('Garter', 1),
 ('Regular Stockings', 1),
 ('Shaping', 1),
 ('Suspender', 1),
 ('Thermal', 1),
 ('Footless', 1)]

## driver method to write attributes and corresponding values to csv file

In [22]:
def gen_attributes_csv_from_df(df,column_name,filename=None,thresh_hold=500):
    attribs=get_attributes_from_df(df,column_name)
    #attribs_dct = {}
    attribs_vals = []
    for attrib in attribs:
        vals = get_vals_for_attrib(attrib,df,column_name)
        attribs_vals.append(vals)
        #attribs_dct[attrib]=vals
    # generate datframe for lst
    attribs_vals_df=pd.DataFrame(attribs_vals,index=attribs).T
    if filename is not None:
        attribs_vals_df.to_csv(filename)
    return attribs_vals_df

## Women Shoes

In [21]:
women_shoes_ids = [11632,45333,53548,53557,55793,62107,95672]
women_shoes_df=main_df[main_df['id'].isin(women_shoes_ids)]

In [22]:
gen_attributes_csv_from_df(women_shoes_df,'REQUIRED')

,Brand,Style,Color,Department,Type,US Shoe Size,Upper Material
0,Unbranded,Ballet,Beige,Teens,Slipper,1,100% Cashmere
1,!it,Bootie,Black,Unisex Adults,Flat,1.5,100% Cotton
2,!Solid,Clog,Blue,Women,Heel,2,100% Silk
3,& Other Stories,Fisherman,Brown,None,Athletic,2.5,100% Wool
4,&Work,Flat,Clear,None,Boot,3,Acetate
...,...,...,...,...,...,...,...
14876,Replica,None,None,None,None,None,None
14877,Senso,None,None,None,None,None,None
14878,Sorbet,None,None,None,None,None,None
14879,White Stuff,None,None,None,None,None,None
14880,WP,None,None,None,None,None,None

In [20]:
get_df_attributes_values(women_shoes_df,'REQUIRED')

,Brand,Style,Color,Department,Type,US Shoe Size,Upper Material
0,Unbranded,Ballet,Beige,Teens,Slipper,1,100% Cashmere
1,!it,Bootie,Black,Unisex Adults,Flat,1.5,100% Cotton
2,!Solid,Clog,Blue,Women,Heel,2,100% Silk
3,& Other Stories,Fisherman,Brown,None,Athletic,2.5,100% Wool
4,&Work,Flat,Clear,None,Boot,3,Acetate
...,...,...,...,...,...,...,...
14876,Replica,None,None,None,None,None,None
14877,Senso,None,None,None,None,None,None
14878,Sorbet,None,None,None,None,None,None
14879,White Stuff,None,None,None,None,None,None
14880,WP,None,None,None,None,None,None

In [21]:
if not os.path.exists('./women_shoes'):
    os.mkdir('women_shoes')

In [22]:
women_shoes_recommended=get_df_attributes_values(women_shoes_df,'RECOMMENDED','./women_shoes/women_shoes_recommended.csv')

In [23]:
women_shoes_optional=get_df_attributes_values(women_shoes_df,'OPTIONAL','./women_shoes/women_shoes_optional.csv')

In [24]:
women_shoes_required=get_df_attributes_values(women_shoes_df,'REQUIRED','./women_shoes/women_shoes_required.csv')

In [25]:
writer = pd.ExcelWriter('./women_shoes/women_shoes_attributes_vals.xlsx', engine='xlsxwriter')

In [26]:
women_shoes_recommended.to_excel(writer, sheet_name='recommended')
women_shoes_optional.to_excel(writer, sheet_name='optional')
women_shoes_required.to_excel(writer, sheet_name='required')

writer.save()

## Hoddies and Jackets

In [66]:
men_hoodies_jackets_ids = [155183,
185702,
105511,
163141,
175771,
182046,
179007,
]

skipped_ids = [20184,
20187,
35840,
60288,
163871,
60378,
164107,
181134,
59353,
59392,
179827,
180135,
]

In [67]:
men_hodies_jackets_df = main_df[main_df['id'].isin(men_hoodies_jackets_ids)]

In [68]:
if not os.path.exists('./new_men_hoodies_jackets'):
    os.mkdir('./new_men_hoodies_jackets')

In [69]:
men_hoodiesjackets_recommended=gen_attributes_csv_from_df(men_hodies_jackets_df,'RECOMMENDED','./new_men_hoodies_jackets/men_hoodiesjackets_recommended.csv')

In [70]:
men_hoodiesjackets_required=gen_attributes_csv_from_df(men_hodies_jackets_df,'REQUIRED','./new_men_hoodies_jackets/men_hoodiesjackets_required.csv')

In [71]:
men_hoodiesjackets_optional=gen_attributes_csv_from_df(men_hodies_jackets_df,'OPTIONAL','./new_men_hoodies_jackets/men_hoodiesjackets_optional.csv')

In [72]:
writer = pd.ExcelWriter('./new_men_hoodies_jackets/men_hoddiesjackets_attributes_vals.xlsx', engine='xlsxwriter')

In [73]:
men_hoodiesjackets_recommended.to_excel(writer, sheet_name='recommended')
men_hoodiesjackets_required.to_excel(writer, sheet_name='required')
men_hoodiesjackets_optional.to_excel(writer, sheet_name='optional')

writer.save()

## Women Tops

In [19]:
women_tops_ids = [53159]
women_tops_df = main_df[main_df['id'].isin(women_tops_ids)]

In [20]:
gen_attributes_csv_from_df(women_tops_df,'RECOMMENDED')

,Style,Neckline,Sleeve Type,Material,Sleeve Length,Pattern,Accents,Theme,Features,Fabric Type,Occasion,Character,Fit,Vintage
0,Basic,Boat Neck,Asymmetrical Sleeve,100% Cotton,Sleeveless,Animal Print,Beaded,20s,1/2 Zip,Canvas,Business,Andrea,Athletic,Yes
1,Camisole,Collared,Balloon Sleeve,100% Merino Wool,Short Sleeve,Argyle/Diamond,Bow,30s,Adjustable,Chambray,Casual,Angel,Classic,No
2,Cropped,Cowl Neck,Bell Sleeve,Acetate,3/4 Sleeve,Camouflage,Buckle,3D,Adjustable Strap,Chiffon,Formal,Astro Boy,Extra-Slim,None
3,Jersey,Crew Neck,Cap Sleeve,Acrylic,Long Sleeve,Check,Button,40s,All Seasons,Corduroy,Party/Cocktail,Atom,Regular,None
4,Kimono,Halter,Cold Shoulder Sleeve,Alfa,None,Colorblock,Crochet,50s,Backless,Crochet,Travel,Barbie,Relaxed,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,None,None,None,None,None,None,None,None,None,None,None,Warrior,None,None
169,None,None,None,None,None,None,None,None,None,None,None,Whitney,None,None
170,None,None,None,None,None,None,None,None,None,None,None,Wonder Girl,None,None
171,None,None,None,None,None,None,None,None,None,None,None,Wonder Woman,None,None
172,None,None,None,None,None,None,None,None,None,None,None,Zoe,None,None

In [21]:
if not os.path.exists('./women_tops'):
    os.mkdir('./women_tops')

In [24]:
women_tops_recommended=gen_attributes_csv_from_df(women_tops_df,'RECOMMENDED','./women_tops/women_tops_recommended.csv')

In [26]:
women_tops_required=gen_attributes_csv_from_df(women_tops_df,'REQUIRED','./women_tops/women_tops_required.csv')

In [27]:
women_tops_optional=gen_attributes_csv_from_df(women_tops_df,'OPTIONAL','./women_tops/women_tops_optional.csv')

In [28]:
writer = pd.ExcelWriter('./women_tops/women_tops_attributes_vals.xlsx', engine='xlsxwriter')

In [29]:
women_tops_recommended.to_excel(writer, sheet_name='recommended')
women_tops_required.to_excel(writer, sheet_name='required')
women_tops_optional.to_excel(writer, sheet_name='optional')

writer.save()

## Men lowers

In [24]:
'''
men_df = final_tree_df[final_tree_df['root 1'].isin(['Men','Specialty'])]
men_lowers = ['Underwear','Shorts','Pants','Pants & Shorts','Swimwear']
men_lowers_df=men_df[men_df['root 3'].isin(men_lowers)]
men_lowers_jsons_ids = list(men_lowers_df['id'])
'''
men_lowers_jsons_ids = [11507, 15689, 15690, 57989, 163525]

In [26]:
tmp_id = [11507]

In [27]:
men_lowers_df = main_df[main_df['id'].isin(tmp_id)]

In [28]:
men_lowers_df

,id,REQUIRED,RECOMMENDED,OPTIONAL
256,11507,"[{'Brand': ['!it', '& Other Stories', '+8000',...","[{'Theme': ['3D', '80s', '90s', 'Aloha', 'Amer...","[{'Pattern': ['Animal Print', 'Argyle/Diamond'..."

In [29]:
gen_attributes_csv_from_df(men_lowers_df,'RECOMMENDED')

,Theme,Material,Character,Fabric Type,Features,Character Family,Vintage,Country/Region of Manufacture
0,3D,Acetate,Andrea,Chiffon,All Seasons,Angry Birds,Yes,Afghanistan
1,80s,Acrylic,Angel,Corduroy,Breathable,Astro Boy,No,Albania
2,90s,Alfa,Astro Boy,Denim,High Leg,Barbie,None,Algeria
3,Aloha,Alginate,Atom,Fleece,Lightweight,Batman,None,American Samoa
4,American,Alpaca,Barbie,Jersey,Preshrunk,Beauty and the Beast,None,Andorra
...,...,...,...,...,...,...,...,...
229,None,None,None,None,None,None,None,Wallis and Futuna
230,None,None,None,None,None,None,None,Western Sahara
231,None,None,None,None,None,None,None,Yemen
232,None,None,None,None,None,None,None,Zambia
233,None,None,None,None,None,None,None,Zimbabwe

In [70]:
if not os.path.exists('./men_lowers'):
    os.mkdir('./men_lowers')

In [71]:
men_lowers_recommended=gen_attributes_csv_from_df(men_lowers_df,'RECOMMENDED','./men_lowers/men_lowers_recommended.csv')
men_lowers_required=gen_attributes_csv_from_df(men_lowers_df,'REQUIRED','./men_lowers/men_lowers_required.csv')
men_lowers_optional=gen_attributes_csv_from_df(men_lowers_df,'OPTIONAL','./men_lowers/men_lowers_optional.csv')

In [72]:
writer = pd.ExcelWriter('./men_lowers/men_lowers_attributes_vals.xlsx', engine='xlsxwriter')
men_lowers_recommended.to_excel(writer, sheet_name='recommended')
men_lowers_required.to_excel(writer, sheet_name='required')
men_lowers_optional.to_excel(writer, sheet_name='optional')

writer.save()